[versions]
agp = "8.8.0"
bdf = "0.5.0-agp8.8.0"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
bdf = { id = "app.cash.better.dynamic.features", version.ref = "bdf" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

